name: Deploy via CodeDeploy & S3

on:
  push:
    branches:
      - pipeline-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip and upload to S3
        run: |
          zip -r app.zip .
          aws s3 cp app.zip s3://ethanwestenskowtestbucket/app.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name CodeDeployDemo \
            --deployment-group-name CodeDeployDemo-Grp \
            --s3-location bucket=ethanwestenskowtestbucket,key=app.zip,bundleType=zip \
            --region us-east-1
